### ISSUE TITLE
Set default value for github_path of 'backdrop-contrib/'

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/github_stats#1]
As the primary use case will be for Backdrop Contrib, please could this be a default value to make it easier to enter.

**Comment by indigoxela** [comment]
Sure, but then the placeholder makes no sense, as it wouldn't be visible.
We'd need some help text then.

This module does work with other (public) repos on Github, btw. :wink: But, yes, the primary use-case is backdrop-contrib.

Mind to file a PR?

**Comment by yorkshire-pudding** [comment]
@indigoxela PR for your consideration

**Comment by indigoxela** [comment]
> PR for your consideration

I considered... and fixed the syntax error :speak_no_evil: 
Many thanks for providing, though. :wink:

**Comment by yorkshire-pudding** [comment]
> I considered... and fixed the syntax error 🙊

Oops - sorry

**Comment by indigoxela** [comment]
> Oops - sorry

Never mind, it was a good reminder to add checks in a GithubAction. :wink:
