### ISSUE TITLE
Either validate github_path before saving or allow edit

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/github_stats#2]
I accidentally typed the github path wrong (including underscores where there were none).  It shows an error but the path can't be edited, so you have to delete the entity and recreate.

I ended up hacking the module to allow edit of github path.

**Comment by indigoxela** [comment]
> ... can't be edited, so you have to delete the entity and recreate.

That's actually by intention. If you change the path, you might end up with nonsense data (fetched data from other repo).

Validation it is...

> ended up hacking the module to allow edit of github path.

Nasty you. :laughing: 

Here's a PR that adds more validation before saving: #3

**Comment by yorkshire-pudding** [comment]
> Nasty you. 😆

😆 

PR tested and works a treat. Thank you!
