### ISSUE TITLE
Usage count

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/github_stats#7]
I tried adding Entity Plus and the usage count shows up as `1`. I suspect that the comma throws things off somehow -- it should be `1,442` at the moment.

**Comment by indigoxela** [comment]
Oops, that's a bug. Didn't consider the thousand marker in that string.

**Comment by indigoxela** [comment]
@laryn does that work for you? #8

**Comment by laryn** [comment]
Tested and works for me!

**Comment by indigoxela** [comment]
Many thanks for reporting and testing. :+1:
